apiVersion: v1
kind: Service
metadata:
  labels:
    control-plane: kwok-operator
    app.kubernetes.io/name: service
    app.kubernetes.io/instance: kwok-operator-metrics-service
    app.kubernetes.io/component: kube-rbac-proxy
    app.kubernetes.io/created-by: kwok-operator
    app.kubernetes.io/part-of: kwok-operator
    app.kubernetes.io/managed-by: kustomize
  name: kwok-operator-metrics-service
  namespace: kwok-operator
spec:
  ports:
  - name: https
    port: 8443
    protocol: TCP
    targetPort: https
  selector:
    control-plane: kwok-operator
