# permissions for end users to view deploymentpools.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: deploymentpool-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: kwok-operator
    app.kubernetes.io/part-of: kwok-operator
    app.kubernetes.io/managed-by: kustomize
  name: deploymentpool-viewer-role
rules:
- apiGroups:
  - kwok.sigs.run-ai.com
  resources:
  - deploymentpools
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - kwok.sigs.run-ai.com
  resources:
  - deploymentpools/status
  verbs:
  - get
