---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kwok-operator-cr
rules:
- apiGroups:
  - ""
  resources:
  - nodes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - kwok.sigs.run-ai.com
  resources:
  - nodepools
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - kwok.sigs.run-ai.com  
  resources:
  - nodepools/finalizers
  verbs:
  - update
- apiGroups:
  - kwok.sigs.run-ai.com
  resources:
  - nodepools/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - kwok.sigs.run-ai.com
  resources:
  - deploymentpools
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - kwok.sigs.run-ai.com
  resources:
  - deploymentpools/status
  - deploymentpools/finalizers
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - get
  - list
  - patch
  - update
  - watch
  - create
  - delete