---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kwok-operator-cr
rules:
- apiGroups:
  - batch
  resources:
  - jobs
  verbs:
  - get
  - list
  - patch
  - update
  - watch
  - create
  - delete
- apiGroups:
  - apps
  resources:
  - deployments
  - daemonsets
  verbs:
  - get
  - list
  - patch
  - update
  - watch
  - create
  - delete
- apiGroups:
  - ""
  resources:
  - nodes
  - pods
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - kwok.sigs.run-ai.com
  resources:
  - nodepools
  - deploymentpools
  - daemonsetpools
  - podpools
  - jobpools
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - kwok.sigs.run-ai.com  
  resources:
  - nodepools/finalizers
  - deploymentpools/finalizers
  - podpools/finalizers
  - jobpools/finalizers
  - daemonsetpools/finalizers
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - kwok.sigs.run-ai.com
  resources:
  - nodepools/status
  - deploymentpools/status
  - podpools/status
  - jobpools/status
  - daemonsetpools/status
  verbs:
  - get
  - patch
  - update
