apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/name: serviceaccount
    app.kubernetes.io/instance: kwok-operator-sa
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: kwok-operator
    app.kubernetes.io/part-of: kwok-operator
    app.kubernetes.io/managed-by: kustomize
  name: kwok-operator-sa
  namespace: kwok-operator
