# permissions for end users to view statefulsetpools.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: statefulsetpool-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: kwok-operator
    app.kubernetes.io/part-of: kwok-operator
    app.kubernetes.io/managed-by: kustomize
  name: statefulsetpool-viewer-role
rules:
- apiGroups:
  - kwok.sigs.run-ai.com
  resources:
  - statefulsetpools
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - kwok.sigs.run-ai.com
  resources:
  - statefulsetpools/status
  verbs:
  - get
